# Generated by Django 5.2 on 2026-08-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('communication', '会話・コミュニケーション編'), ('cleanliness', '清潔感・身だしなみ編'), ('date', 'デート・距離感編'), ('mental', 'メンタル・余裕編')], max_length=50),
        ),
    ]
